blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/sandraschi/database-operations-mcp/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issue
    url: https://github.com/sandraschi/database-operations-mcp/security/advisories/new
    about: Report a security vulnerability (private disclosure)
  - name: 📚 Documentation
    url: https://github.com/sandraschi/database-operations-mcp#readme
    about: View the project documentation
