name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! We appreciate your ideas to make this project better.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: Alternatively, we could...
    validations:
      required: false

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area of the project does this feature relate to?
      multiple: true
      options:
        - Database Operations
        - MCP Tools
        - Connection Management
        - Query Building
        - Data Export/Import
        - Schema Management
        - Windows Integration
        - Media Server Integration
        - Documentation
        - Testing
        - Performance
        - Security
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would significantly improve workflow
        - High - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: I need this feature because...
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature would work
      placeholder: |
        ```python
        # Example usage
        result = mcp_server.new_feature()
        ```
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request
      placeholder: Any additional information
    validations:
      required: false

