name: DXT Build and Test

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'dxt/**'
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'setup.py'
      - 'requirements*.txt'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'dxt/**'
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'setup.py'
      - 'requirements*.txt'

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
        pip install dxt
        
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 src tests dxt --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src tests dxt --count --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Run unit tests
      run: |
        python -m pytest tests/unit -v --cov=src --cov-report=xml
        
    - name: Run DXT tests
      run: |
        python -m pytest dxt/tests -v
        
    - name: Build DXT package
      run: |
        mkdir -p dist
        powershell -ExecutionPolicy Bypass -File dxt/build.ps1
        
    - name: Upload DXT package
      uses: actions/upload-artifact@v3
      with:
        name: dxt-package
        path: dist/*.dxt
        if-no-files-found: error
        
    - name: Validate DXT package
      run: |
        $dxtFile = Get-ChildItem -Path dist -Filter "*.dxt" | Select-Object -First 1
        if (-not $dxtFile) { 
            Write-Error "No DXT file found in dist directory"
            exit 1 
        }
        dxt validate $dxtFile.FullName
