name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        default: '0.1.0'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install --upgrade dxt
    
    - name: Build Python package
      run: python -m build
    
    - name: Verify DXT installation
      run: |
        python -m pip show dxt || echo "DXT not installed"
        python -c "import dxt; print(f'DXT version: {dxt.__version__}' if hasattr(dxt, '__version__') else 'DXT version not found')" || echo "Failed to import dxt"
        
    - name: Build DXT package
      run: |
        mkdir -p dist
        python -m dxt pack -o dist/database-operations-mcp.dxt || echo "DXT pack failed"
        ls -la dist/ || echo "No dist directory"
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: Release v${{ github.event.inputs.version }}
        body: |
          Release v${{ github.event.inputs.version }}
          
          ### Changes
          - Update package version to ${{ github.event.inputs.version }}
        files: |
          dist/*
        generate_release_notes: true
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
