name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        default: '0.1.0'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '18'
    
    - name: Install MCPB CLI
      run: npm install -g @anthropic-ai/mcpb
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    
    - name: Build Python package
      run: python -m build
    
    - name: Build MCPB package
      run: |
        mkdir -p dist
        cd mcpb
        mcpb pack . ../dist/database-operations-mcp.mcpb
        cd ..
        ls -la dist/ || echo "No dist directory"
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: Release v${{ github.event.inputs.version }}
        body: |
          Release v${{ github.event.inputs.version }}
          
          ### Changes
          - Update package version to ${{ github.event.inputs.version }}
        files: |
          dist/*
        generate_release_notes: true
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
