name: Release Workflow

on:
  push:
    tags:
      - 'v*.*.*'  # Matches tags like v1.0.0, v2.1.3, etc.

# Skip workflow if triggered by a tag push
# This prevents the workflow from running in a loop
if: "!startsWith(github.ref, 'refs/tags/v')

# Prevent workflow from running multiple times for the same tag
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build dxt
    
    - name: Build Python package
      run: python -m build
    
    - name: Build DXT package
      run: |
        mkdir -p dist
        dxt pack -o dist/database-operations-mcp.dxt
        
    - name: Create GitHub Release
      # Skip if the release already exists
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.whl
          dist/*.tar.gz
          dist/*.dxt
        generate_release_notes: true
        fail_on_unmatched_files: false  # Don't fail if some files are missing
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
