name: Release Workflow

on:
  push:
    tags:
      - 'v*.*.*'  # Matches tags like v1.0.0, v2.1.3, etc.

# Prevent workflow from running multiple times for the same tag
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '18'
    
    - name: Install MCPB CLI
      run: npm install -g @anthropic-ai/mcpb
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    
    - name: Build Python package
      run: python -m build
    
    - name: Build MCPB package
      run: |
        mkdir -p dist
        cd mcpb
        mcpb pack . ../dist/database-operations-mcp.mcpb
        cd ..
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.whl
          dist/*.tar.gz
          dist/*.mcpb
        generate_release_notes: true
        fail_on_unmatched_files: false  # Don't fail if some files are missing
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
